name: Build SkyblockMulti

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'

  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.5.0'

      - name: Build
        run: gradle build --stacktrace

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SkyblockMulti-build
          path: build/libs/*.jar
          if-no-files-found: error
